create table if not exists users (
                       id bigint generated by default as identity primary key,
                       username varchar(50) not null unique,
                       email varchar(50) not null unique,
                       password varchar(255) not null,
                       role varchar(20) not null
);
